services:
  backend:
    image: cred7/gorbackend:latest
    # build:
    #   context: ./gorbackend
    container_name: django-backend
    environment:
      REDIS_URL: "redis://redis:6379/1"
      HOST: "postgres"
      PORT: "5432"
      CELERY_BROKER: "amqp://guest:guest@rabbitmq:5672//"
    volumes:
      - ./gorbackend:/app
    ports:
      - "7000:7000"
    depends_on:
      - postgres
      - redis
    command: >
      sh -c "python manage.py migrate &&
             daphne -b 0.0.0.0 -p 7000 core.asgi:application"

  frontend:
    image: cred7/webrepo:latest
    # build:
    #   context: ./web
    container_name: nextjs-frontend
    # volumes:
    #   - ./web:/app
    #   - /app/node_modules
    ports:
      - "4000:4000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:7000
      NEXT_PUBLIC_WS_API_URL: ws://localhost:7000
      API_URL: http://backend:7000
      PORT: 4000
    depends_on:
      - backend

  redis:
    image: redis:latest
    container_name: gor-redis-cache
    ports:
      - "6379:6379"
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  celery:
    image: cred7/gorbackend:latest
    # build:
    #   context: ./gorbackend
    container_name: celery_worker
    environment:
      REDIS_URL: "redis://redis:6379/1"
      HOST: "postgres"
      PORT: "5432"
      CELERY_BROKER: "amqp://guest:guest@rabbitmq:5672//"
    volumes:
      - ./gorbackend:/app
    command: celery -A gorbackend worker -l info
    depends_on:
      - backend
      - rabbitmq

  postgres:
    image: postgres
    container_name: gormahia-backend
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gorbackend
    ports:
      - "5455:5432"
    volumes:
      - pg_gor:/var/lib/postgresql/data

volumes:
  pg_gor:
    external: true
    name: gorbackend_pg_gor
